export const createMenuState = () => ({
  mealPlan: [],
  menu: [],
});

// export const createMenuState = () => ({
//   mealPlan: [],
//   menu: [
//     {
//       name: 'Dish 1',
//       id: 1,
//       picture: undefined,
//       cals: 100,
//       protein: 15,
//       carbs: 10,
//       fat: 5,
//       liked: false,
//       disliked: false,
//     },
//     {
//       name: 'Dish 2',
//       id: 2,
//       picture: undefined,
//       cals: 200,
//       protein: 25,
//       carbs: 20,
//       fat: 15,
//       liked: false,
//       disliked: false,
//     },
//     {
//       name: 'Dish 3',
//       id: 3,
//       picture: undefined,
//       cals: 300,
//       protein: 35,
//       carbs: 30,
//       fat: 25,
//       liked: false,
//       disliked: false,
//     },
//     {
//       name: 'Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 Dish4 ',
//       id: 4,
//       picture: undefined,
//       cals: 400,
//       protein: 45,
//       carbs: 40,
//       fat: 35,
//       liked: false,
//       disliked: false,
//     },
//     {
//       name: 'Dish 5',
//       id: 5,
//       picture: undefined,
//       cals: 500,
//       protein: 55,
//       carbs: 50,
//       fat: 45,
//       liked: false,
//       disliked: false,
//     },
//     {
//       name: 'Dish 10',
//       id: 6,
//       picture: undefined,
//       cals: 100,
//       protein: 15,
//       carbs: 10,
//       fat: 5,
//       liked: false,
//       disliked: false,
//     },
//     {
//       name: 'Dish 20',
//       id: 7,
//       picture: undefined,
//       cals: 200,
//       protein: 25,
//       carbs: 20,
//       fat: 15,
//       liked: false,
//       disliked: false,
//     },
//     {
//       name: 'Dish 30',
//       id: 8,
//       picture: undefined,
//       cals: 300,
//       protein: 35,
//       carbs: 30,
//       fat: 25,
//       liked: false,
//       disliked: false,
//     },
//     {
//       name: 'Dish 40',
//       id: 9,
//       picture: undefined,
//       cals: 400,
//       protein: 45,
//       carbs: 40,
//       fat: 35,
//       liked: false,
//       disliked: false,
//     },
//     {
//       name: 'Dish 50',
//       id: 10,
//       picture: undefined,
//       cals: 500,
//       protein: 55,
//       carbs: 50,
//       fat: 45,
//       liked: false,
//       disliked: false,
//     },
//   ],
// });
