export const createMenuState = () => [
  {
    name: 'Dish 1',
    picture: undefined,
    cals: 100,
    protein: 15,
    carbs: 10,
    fat: 5,
    liked: false,
    disliked: false,
  },
  {
    name: 'Dish 2',
    picture: undefined,
    cals: 200,
    protein: 25,
    carbs: 20,
    fat: 15,
    liked: false,
    disliked: false,
  },
  {
    name: 'Dish 3',
    picture: undefined,
    cals: 300,
    protein: 35,
    carbs: 30,
    fat: 25,
    liked: false,
    disliked: false,
  },
  {
    name: 'Dish 4',
    picture: undefined,
    cals: 400,
    protein: 45,
    carbs: 40,
    fat: 35,
    liked: false,
    disliked: false,
  },
  {
    name: 'Dish 5',
    picture: undefined,
    cals: 500,
    protein: 55,
    carbs: 50,
    fat: 45,
    liked: false,
    disliked: false,
  },
];
